name: 'VenafiPS'
description: 'Automate against Venafi Trust Protection Platform and Venafi as a Service with the VenafiPS Powershell module, https://github.com/Venafi/VenafiPS'
author: 'Greg Brownstein'
inputs:
  TPP_TOKEN:
    description: TPP token
    required: false
  TPP_SERVER:
    description: TPP server name
    required: false
  VAAS_KEY:
    description: VaaS key
    required: false
output:
  action_out:
  description: 'Output from action to be used further in the pipeline'
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: terminal
  color: orange