name: 'VenafiPS'
description: 'Execute commands from VenafiPS Powershell module'
author: 'Greg Brownstein'
inputs:
  token:
    description: TPP token or VaaS key
    required: true
  server:
    description: TPP server name.  Not required for VaaS.
    required: false
  commands:
    description: Module commands to execute
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
#   args:
#     - ${{ inputs.myInput }}
