name: 'Container Action Template'
description: 'Get started with Container actions'
author: 'Greg Brownstein'
inputs:
  token:
    description:
    required: true
  server:
    description:
    required: false
  commands:
    description:
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
#   args:
#     - ${{ inputs.myInput }}
